Parameters:
  GitHubORG:
    Type: String
  RepositoryName:
    Type: String
  OIDCProviderArn:
    Default: ""
    Type: String
  OIDCAudience:
    Default: "sts.amazonaws.com"
    Type: String

Conditions:
  BuildOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName:          # Todo: Add Parameter
      ManagedPolicyArns: ["arn:aws:iam::aws:policy/AdministratorAccess"] # Todo
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - BuildOIDCProvider
                - !Ref OIDCProviderArn
                - !Ref GithubOIDC
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubORG}/${RepositoryName}:*
              StringLike:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience

  GithubOIDC:
    Type: AWS::IAM::OIDCProvider
    Condition: BuildOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: ["6938fd4d98bab03faadb97b34396831e3780aea1"]
      ClientIdList:   ["sts.amazonaws.com"]
    # {...}

# {...}
