name: cd-template

on:
  workflow_call:
    inputs:
      environment:
        type: string

jobs:
  cd:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    defaults:
      run:
        working-directory: ./terraform/${{inputs.environment}}
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@v2
      #   with:
      #     egress-policy: block
      - name: Check-Out
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region:     ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform-init
        run:  terraform init

#     - tf-diff # => Create/Update diff as Comment in PR

      - name: terraform-apply
        run:  terraform apply --auto-approve

#       Job running daily?
#     - smoke-tests
#     - ...
#   ...
# ...
