name: cicd

# Flows: => Environment Separation
# - Default Branch (main)
# - Feature Branch
# - Pull Request

# Todos:
# - Release.yml

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
    steps:
      - name: Check-Out
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
          pipx install poetry==1.4.0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # => Required by λ-Service
          cache: poetry
      - name: Install all (Dev-)Dependencies
        run: |
          poetry install
      - name: Run pylint
        run: |
          poetry run pylint vehicle_api/
      - name: Run unit-tests
        run: |
          poetry run coverage run -m pytest tests/unit
          poetry run coverage report -m
      - name: Run intr-tests
        run: |
          poetry run coverage run -m pytest tests/intr
          poetry run coverage report -m
  cd:
    runs-on: ubuntu-latest
    needs: ci
    environment: qa # Todo
    defaults:
      run:
        working-directory: ./terraform/qa # Todo
    permissions:
      id-token: write
      contents: write
    steps:
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region:     eu-west-1
          role-to-assume: arn:aws:iam::292372118261:role/my-github-actions-role
      - name: Check-Out
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: terraform-init
        run:  terraform init
#     - tf-validate
#     - tf-diff # => Create/Update diff as Comment in PR
      - name: terraform-apply
        run:  terraform apply --auto-approve

#     - smoke-tests
#     - ...
#   ...
# ...
