name: cicd-prod

on:
  # workflow_dispatch: <>
  pull_request:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  id-token:      write
  contents:      write

jobs:
  ci-prod:
    uses: dschro-1993/vehicle-api-workflows/.github/workflows/ci.yml@0.1.0
  cd-prod:
    uses: dschro-1993/vehicle-api-workflows/.github/workflows/cd.yml@0.1.0
    with:
      dir:    terraform/prod
      env:    prod
      github: ${{github}}
    secrets: inherit
    needs:   ci-prod
