name: cicd-qa

on:
  # workflow_dispatch: <>
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  ci-qa:
    uses: .github/workflows/ci.yml@main
    secrets: inherit
    with:
      # ${{github.event.inputs.environment}}
      env: qa
  cd-qa:
    uses: .github/workflows/cd.yml@main
    needs: ci-qa
    secrets: inherit
    with:
      # ${{github.event.inputs.environment}}
      env: qa
