name: cicd-qa

on:
  # workflow_dispatch: <>
  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  ci-qa:
    uses: dschro-1993/vehicle-api-workflows/.github/workflows/ci.yml@0.1.0
  cd-qa:
    uses: dschro-1993/vehicle-api-workflows/.github/workflows/cd.yml@0.1.0
    with:
      dir:        terraform/qa
      env:        qa
      event-name: ${{github.event_name}}
    secrets: inherit
    needs:   ci-qa
