name: cicd-qa

on:
  push:
    branches-ignore:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    uses: dschro-1993/vehicle-api-workflows/.github/workflows/ci.yml@0.1.0
  cd:
    needs: ci
    secrets: inherit
    uses: dschro-1993/vehicle-api-workflows/.github/workflows/cd.yml@0.1.0
    with:
      backend:  tfvars/qa/backend.conf
      var-file: tfvars/qa/api.tfvars
      env:      qa
    
  # {...}

# {...}
