name: cicd-qa

on:
  # workflow_dispatch: <>
  push:
    branches-ignore:
      - main

permissions:
  pull-requests: write
  id-token:      write
  contents:      write

environment: qa

jobs:
  ci-qa:
    uses: dschro-1993/vehicle-api/.github/workflows/ci.yml@0.1.0
  cd-qa:
    uses: dschro-1993/vehicle-api/.github/workflows/cd.yml@0.1.0
    with:
      working-directory: .terraform/qa
    secrets: inherit
    needs:   ci-qa
